-- PostgreSQL script
-- Enums
CREATE TYPE trainer_status_enum AS ENUM ('Active', 'Inactive', 'On-Leave');
CREATE TYPE class_level_enum AS ENUM ('Beginner', 'Intermediate', 'Advanced');
CREATE TYPE training_status_enum AS ENUM ('Scheduled', 'In Progress', 'Completed', 'Cancelled');

-- Tables
CREATE TABLE trainer (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    speciality VARCHAR(50),
    phone VARCHAR(20),
    email VARCHAR(50),
    status trainer_status_enum DEFAULT 'Active' NOT NULL
);

CREATE TABLE trainer_availability (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    trainer_id INTEGER NOT NULL,
    date TIMESTAMP NOT NULL,
    start_time TIME,
    end_time TIME,
    is_available BOOLEAN DEFAULT true NOT NULL
);

CREATE TABLE class (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    class_name VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    level class_level_enum DEFAULT 'Beginner' NOT NULL,
    capacity INTEGER CHECK( capacity > 0 ),
    duration INTEGER NOT NULL CHECK( duration > 0 ),

    -- This column is generated by the database and CANNOT be overwritten by a user
    duration_unit VARCHAR(10) GENERATED ALWAYS AS ('Minutes') STORED
);

CREATE TABLE trainer_class (
    trainer_id INTEGER NOT NULL,
    class_id INTEGER NOT NULL,
    assigned_date date,

    PRIMARY KEY (trainer_id, class_id)
);

CREATE TABLE personal_training (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    trainer_id INTEGER NOT NULL,
    member_id INTEGER NOT NULL,
    start_date_time TIMESTAMP NOT NULL,
    duration INTEGER CHECK( duration > 0 ),
    status training_status_enum DEFAULT 'Scheduled' NOT NULL,
    notes VARCHAR(60),

    -- This column is generated by the database and CANNOT be overwritten by a user
    duration_unit VARCHAR(10) GENERATED ALWAYS AS ('Minutes') STORED
);
