-- PostgreSQL script
-- Enums
CREATE TYPE equipment_status_enum AS ENUM ('Maintained', 'Broken', 'In-Repair');
CREATE TYPE common_status_enum AS ENUM ('Scheduled', 'In Progress', 'Completed');

-- Tables
CREATE TABLE public.fitness_floor (
    floor_number integer PRIMARY KEY,
    floor_name varchar(20) NOT NULL
);

CREATE TABLE public.fitness_room (
    room_id integer PRIMARY KEY,
    floor_number integer NOT NULL,
    room_name varchar(20) NOT NULL,
    room_type varchar(20) NOT NULL,
    door_number integer NOT NULL,
    max_capacity integer NOT NULL CHECK( max_capacity > 0)
);

CREATE TABLE public.equipment (
    id integer PRIMARY KEY,
    name varchar(20) NOT NULL,
    status_id integer NOT NULL,
    quantity integer NOT NULL CHECK( quantity >= 0)
);

CREATE TABLE public.equipment_status (
    id integer PRIMARY KEY,
    status equipment_status_enum DEFAULT 'Maintained' NOT NULL
);

CREATE TABLE public.room_equipment (
    room_id integer NOT NULL,
    equipment_id integer NOT NULL,

    PRIMARY KEY(room_id, equipment_id)
);

CREATE TABLE public.cleaning_schedule (
    id integer PRIMARY KEY,
    room_id integer NOT NULL,
    cleaner_id integer NOT NULL,
    status common_status_enum DEFAULT 'Scheduled' NOT NULL,
    cleaning_date timestamp NOT NULL,
    duration integer NOT NULL CHECK( duration > 0),

    -- This column is generated by the database and CANNOT be overwritten by a user
    duration_unit VARCHAR(10) DEFAULT 'Minutes' NOT NULL CHECK (duration_unit = 'Minutes')
);

CREATE TABLE public.maintenance_schedule (
    id integer PRIMARY KEY,
    maintainer_id integer NOT NULL,
    equipment_id integer NOT NULL,
    status common_status_enum DEFAULT 'Scheduled' NOT NULL,
    maintenance_date timestamp  NOT NULL,
    duration integer  NOT NULL CHECK( duration > 0),

    -- This column is generated by the database and CANNOT be overwritten by a user
	duration_unit VARCHAR(10) DEFAULT 'Minutes' NOT NULL CHECK (duration_unit = 'Minutes')
);
