-- PostgreSQL script
-- Enums
CREATE TYPE trainer_status AS ENUM ('Active', 'Inactive', 'On-Leave');
CREATE TYPE class_level AS ENUM ('Beginner', 'Intermediate', 'Advanced', 'All Levels');
CREATE TYPE training_status AS ENUM ('Scheduled', 'In Progress', 'Completed', 'Cancelled');

-- Tables
CREATE TABLE Trainer (
    id integer PRIMARY KEY,
    first_name varchar(50) NOT NULL,
    last_name varchar(50) NOT NULL,
    speciality varchar(50),
    phone varchar(20),
    email varchar(50),
    status trainer_status DEFAULT 'Active' NOT NULL
);

CREATE TABLE TrainerAvailability (
    id integer PRIMARY KEY,
    trainer_id integer NOT NULL,
    date timestamp NOT NULL,
    start_time time,
    end_time time,
    is_available boolean DEFAULT true
);

CREATE TABLE Class (
    id integer PRIMARY KEY,
    class_name varchar(50),
    description varchar(255),
    level class_level DEFAULT 'All Levels',
    capacity integer CHECK( capacity > 0 ),
    duration integer NOT NULL CHECK( duration > 0 ),

    -- This column is generated by the database and CANNOT be overwritten by a user
    duration_unit VARCHAR(10) GENERATED ALWAYS AS ('Minutes') STORED
);

CREATE TABLE TrainerClass (
    id integer PRIMARY KEY,
    trainer_id integer NOT NULL,
    class_id integer NOT NULL,
    assigned_date date,

    CONSTRAINT uq_trainer_class UNIQUE (trainer_id, class_id)
);

CREATE TABLE PersonalTraining (
    id integer PRIMARY KEY,
    trainer_id integer NOT NULL,
    member_id integer NOT NULL,
    start_date_time timestamp,
    duration integer CHECK( duration > 0 ),
    status training_status DEFAULT 'Scheduled',
    notes text,

    -- This column is generated by the database and CANNOT be overwritten by a user
    duration_unit VARCHAR(10) GENERATED ALWAYS AS ('Minutes') STORED
);