// Sofia Hrebeniuk — Member Module ER Diagram (Member, Attendance, MemberExperience, Goals, PersonalProgress,MetricType)
// --- MVP TABLES ---

Table Member {
  id integer [primary key]
  first_name varchar [not null]
  last_name varchar [not null]
  experience_id integer [not null]
}

Table Attendance {
  id integer [primary key]
  member_id integer
  attendance_date datetime
}

// --- EXTENDED TABLES / TRACKING ---

Table MemberExperience {
  id integer [primary key]
  level varchar // newbie, experienced, professional
}

Table Goals {
  id integer [primary key]
  member_id integer
  goal_description varchar
  target_date date
}

Table MetricType {
  id integer [primary key]
  metric_name varchar [not null]
  unit varchar
}

Table PersonalProgress {
  id integer [primary key]
  member_id integer [not null]
  metric_type_id integer [not null]
  metric_value float [not null]
  notes text
  progress_date datetime [not null]
}

// --- RELATIONSHIPS ---

Ref: Member.experience_id > MemberExperience.id
Ref: Attendance.member_id > Member.id
Ref: Goals.member_id > Member.id
Ref: PersonalProgress.member_id > Member.id
Ref: PersonalProgress.metric_type_id > MetricType.id
Ref: ClientMemberships.member_id > Member.id
Ref: ClassRegistrations.member_id > Member.id
Ref: Personal_training.member_id > Member.id

// Andrii Prymak - Trainer Module ER Diagram

Table trainer {
  id integer [primary key]
  first_name varchar
  last_name varchar
  speciality varchar
  phone varchar
  email varchar
  status varchar
}

Table trainer_availability {
  id integer [primary key]
  trainer_id integer [not null]
  day_of_week varchar
  start_time time
  end_time time
  is_available boolean
}

Table class {
  id integer [primary key]
  class_name varchar
  description text
  level varchar
  capacity integer
  duration integer
}

Table trainer_class {
  id integer [primary key]
  trainer_id integer [not null]
  class_id integer [not null]
  assigned_date date

  indexes {
    (trainer_id, class_id) [unique]
  }
}

Table personal_training {
  id integer [primary key]
  trainer_id integer [not null]
  visitor_id integer [not null]
  start_date_time timestamp
  duration integer
  status varchar
  notes text
}

Ref: trainer_availability.trainer_id > trainer.id
Ref: trainer_class.trainer_id > trainer.id
Ref: trainer_class.class_id > class.id
Ref: personal_training.trainer_id > trainer.id

//-- End of Andrii Prymak


// Anastasiia Boyko - Staff Module ER Diagram

Table Staff {
  id integer [primary key, increment]
  first_name varchar [not null]
  last_name varchar [not null]
  title varchar [not null]
}

Table FrontdeskShifts {
  id integer [primary key, increment]
  staff_id integer
  start datetime [not null]
  end datetime [not null]
}


Table MembershipPlans {
  id integer [primary key, increment]
  name varchar [not null]
  type varchar [not null]
  price decimal(10,2) [not null]
  discount decimal(10,2) [default: 0]
}

Table ClientMemberships {
  id integer [primary key, increment]
  member_id integer [not null]
  plan_id integer [not null]
  start_date date [not null]
  end_date date [not null]
  status varchar [not null, default: 'Active']
}

Table ClassSchedule {
  id integer [primary key, increment]
  class_id integer [not null]
  room_id integer [not null]
  trainer_id integer [not null]
  date date [not null]
  time time [not null]
}

Table ClassRegistrations {
  id integer [primary key, increment]
  schedule_id integer [not null]
  member_id integer [not null]
}

Ref: FrontdeskShifts.staff_id > Staff.id
Ref: ClientMemberships.plan_id > MembershipPlans.id
Ref: ClassRegistrations.schedule_id > ClassSchedule.id

// Andrii Prymak (Trainer)
Ref: ClassSchedule.class_id > class.id
Ref: ClassSchedule.trainer_id > trainer.id

// VladyslavTupikin (Fitness room)
Ref: CleaningSchedule.cleaner_id > Staff.id
Ref: MaintenanceSchedule.maintainer_id > Staff.id
Ref: ClassSchedule.room_id > FitnessRoom.room_id
//-- End of Anastasiia Boyko


// Vladyslav Tupikin - Fitness Room Module ER Diagram

Table FitnessFloor {
  floor_number integer [primary key]
  floor_name varchar [not null]
}

Table FitnessRoom {
  room_id integer [primary key]
  floor_number integer [not null]
  room_name varchar [not null, note: 'Yoga or Gym or pool']
  room_type varchar [not null]
  door_number integer [not null]
}

Table Equipment {
  id integer [primary key]
  name varchar
  status_id integer [not null]
}

Table EquipmentStatus {
  id integer [primary key]
  status varchar [not null, note: 'Maintained, Broken, In-Repair', default: 'Broken']
}

Table RoomEquipment {
  id integer [primary key, increment]
  room_id integer [not null]
  equipment_id integer [not null]
  equipment_number integer

  indexes {
    (room_id, equipment_id) [unique]  // Унікальна комбінація
  }
}


Table CleaningSchedule {
  id integer [primary key]
  room_id integer [not null]
  cleaner_id integer [not null]
  status varchar [not null, note: 'Scheduled, In Progress, Completed', default: 'Scheduled']
  cleaning_date date
  start_time time
  end_time time
}

Table MaintenanceSchedule {
  id integer [primary key]
  maintainer_id integer [not null]
  equipment_id integer [not null]
  status varchar [not null, note: 'Scheduled, In Progress, Completed', default: 'Scheduled']
  maintenance_date date
  start_time time
  end_time time
}


Ref: FitnessRoom.floor_number > FitnessFloor.floor_number
Ref: RoomEquipment.room_id > FitnessRoom.room_id
Ref: RoomEquipment.equipment_id > Equipment.id
Ref: CleaningSchedule.room_id > FitnessRoom.room_id
Ref: Equipment.status_id > EquipmentStatus.id
Ref: MaintenanceSchedule.equipment_id > Equipment.id

//-- End of Vladyslav Tupikin
