Table FitnessFloor {
  floor_number integer [primary key]
  floor_name text [not null]
}

Table FitnessRoom {
  room_id integer [primary key]
  floor_number integer [not null]
  room_name text [not null, note: 'Yoga or Gym or pool']
  room_type text [not null]
  class_assigned text
  door_number integer [not null]
  clean_schedule_id integer [not null]
}

Table Equipment {
  id integer [primary key]
  name text
  status_id integer [not null]
}

Table EquipmentStatus {
  id integer [primary key]
  status text [not null, note: 'Maintained, Broken, In-Repair']
}

Table RoomEquipment {
  room_id integer [primary key]
  equipment_id integer [primary key]
  equipment_number integer
}


Table CleaningSchedule {
  id integer [primary key]
  room_id integer [not null]
  cleaner_id integer [not null]
  status text [note: 'Cleaning in process or done']
  cleaning_date date
  start_time time
  end_time time
}

Table MaintenanceSchedule {
  id integer [primary key]
  maintainer_id integer [not null]
  equipment_id integer [not null]
  status text [note: 'Maintenance in process or done']
  maintenance_date date
  start_time time
  end_time time
}


Ref: FitnessFloor.floor_number < FitnessRoom.floor_number
Ref: FitnessRoom.room_id < RoomEquipment.room_id
ref: RoomEquipment.equipment_id > Equipment.id
Ref: FitnessRoom.room_id < CleaningSchedule.room_id
Ref: Equipment.status_id > EquipmentStatus.id
Ref: MaintenanceSchedule.equipment_id > Equipment.id
